CREATE TABLE customer
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    cpf        VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    zip_code   VARCHAR(255)                            NOT NULL,
    strett     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_cliente PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT uc_tb_cliente_cpf UNIQUE (cpf);

ALTER TABLE customer
    ADD CONSTRAINT uc_tb_cliente_email UNIQUE (email);