CREATE TABLE credit
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_code            UUID                                    NOT NULL,
    credit_value           DECIMAL                                 NOT NULL,
    day_first_installment  date                                    NOT NULL,
    number_of_installments INT                                     NOT NULL,
    status                 SMALLINT,
    customer_id            BIGINT,
    CONSTRAINT pk_tb_credito PRIMARY KEY (id)
);

ALTER TABLE credit
    ADD CONSTRAINT FK_TB_CREDITO_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);